imports:
    - { resource: tables.yml }
services:
    ajay.bhasha.migrations.ajay_bhasha_controller:
        class: ajay\bhasha\migrations\ajay_bhasha_controller
        arguments:
            - @config
            - @controller.helper
            - @request
            - @template
            - @user
            - @auth
            - @dbal.conn
            - %core.php_ext%
    ajay.bhasha.migrations.myModule:
        class: ajay\bhasha\migrations\myModule
        arguments:
            - @config
            - @controller.helper
            - @request
            - @template
            - @user
            - @auth
            - @dbal.conn
            - %core.php_ext%
    ajay.bhasha.migrations.myTables:
        class: ajay\bhasha\migrations\myTables
        arguments:
            - @config
            - @controller.helper
            - @request
            - @template
            - @user
            - @auth
            - @dbal.conn
            - %core.php_ext%
    ajay.bhasha.listener:
        class: ajay\bhasha\event\listener
        arguments:
            - @config
            - @controller.helper
            - @request
            - @template
            - @user
            - @auth
            - @dbal.conn
            - %core.php_ext%
        tags:
            - { name: event.listener }